import { getPool } from '../database/simple-connection';
import { ClipboardItem, ClipboardCollection } from '../types';
import { logger } from '../utils/logger';
import { v4 as uuidv4 } from 'uuid';

class CollectionsService {
  async createCollection(
    userId: string, 
    name: string, 
    description?: string, 
    autoGenerated = false
  ): Promise<ClipboardCollection> {
    const pool = getPool();
    const id = uuidv4();
    
    const result = await pool.query(
      `INSERT INTO clipboard_collections (id, user_id, name, description, auto_generated, created_at, updated_at)
       VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
       RETURNING *`,
      [id, userId, name, description, autoGenerated]
    );

    return {
      id: result.rows[0].id,
      userId: result.rows[0].user_id,
      name: result.rows[0].name,
      description: result.rows[0].description,
      items: [],
      tags: result.rows[0].tags || [],
      createdAt: result.rows[0].created_at,
      updatedAt: result.rows[0].updated_at,
      autoGenerated: result.rows[0].auto_generated
    };
  }

  async addItemToCollection(collectionId: string, itemId: string): Promise<void> {
    const pool = getPool();
    
    await pool.query(
      `INSERT INTO collection_items (collection_id, item_id, added_at)
       VALUES ($1, $2, NOW())
       ON CONFLICT (collection_id, item_id) DO NOTHING`,
      [collectionId, itemId]
    );

    // Update collection timestamp
    await pool.query(
      'UPDATE clipboard_collections SET updated_at = NOW() WHERE id = $1',
      [collectionId]
    );
  }

  async removeItemFromCollection(collectionId: string, itemId: string): Promise<void> {
    const pool = getPool();
    
    await pool.query(
      'DELETE FROM collection_items WHERE collection_id = $1 AND item_id = $2',
      [collectionId, itemId]
    );
  }

  async getUserCollections(userId: string): Promise<ClipboardCollection[]> {
    const pool = getPool();
    
    const result = await pool.query(
      `SELECT c.*, 
              COALESCE(
                json_agg(
                  CASE WHEN ci.item_id IS NOT NULL THEN ci.item_id END
                ) FILTER (WHERE ci.item_id IS NOT NULL), 
                '[]'
              ) as items
       FROM clipboard_collections c
       LEFT JOIN collection_items ci ON c.id = ci.collection_id
       WHERE c.user_id = $1
       GROUP BY c.id
       ORDER BY c.updated_at DESC`,
      [userId]
    );

    return result.rows.map(row => ({
      id: row.id,
      userId: row.user_id,
      name: row.name,
      description: row.description,
      items: row.items || [],
      tags: row.tags || [],
      createdAt: row.created_at,
      updatedAt: row.updated_at,
      autoGenerated: row.auto_generated
    }));
  }

  async suggestCollections(userId: string, newItem: ClipboardItem): Promise<ClipboardCollection[]> {
    try {
      // Get recent items to analyze patterns
      const pool = getPool();
      const recentItems = await pool.query(
        `SELECT * FROM clipboard_items 
         WHERE user_id = $1 AND created_at > NOW() - INTERVAL '7 days'
         ORDER BY created_at DESC LIMIT 20`,
        [userId]
      );

      const suggestions: ClipboardCollection[] = [];

      // Analyze content for potential collections
      const contentAnalysis = this.analyzeContentForCollections(newItem, recentItems.rows);
      
      for (const analysis of contentAnalysis) {
        if (analysis.confidence > 0.7) {
          // Check if collection already exists
          const existing = await this.findExistingCollection(userId, analysis.name);
          if (!existing) {
            suggestions.push({
              id: `suggestion_${Date.now()}_${Math.random()}`,
              userId,
              name: analysis.name,
              description: analysis.description,
              items: analysis.relatedItems,
              tags: analysis.tags,
              createdAt: new Date(),
              updatedAt: new Date(),
              autoGenerated: true
            });
          }
        }
      }

      return suggestions;
    } catch (error) {
      logger.error('Error suggesting collections:', error);
      return [];
    }
  }

  private analyzeContentForCollections(newItem: ClipboardItem, recentItems: any[]): any[] {
    const analyses: any[] = [];

    // URL-based collections
    if (newItem.contentType === 'url' || newItem.content.includes('http')) {
      const domain = this.extractDomain(newItem.content);
      if (domain) {
        const relatedUrls = recentItems.filter(item => 
          item.content.includes(domain) && item.id !== newItem.id
        );
        
        if (relatedUrls.length >= 2) {
          analyses.push({
            name: `${domain} Research`,
            description: `Links and content from ${domain}`,
            confidence: 0.8,
            relatedItems: [newItem.id, ...relatedUrls.map(item => item.id)],
            tags: ['research', 'urls', domain]
          });
        }
      }
    }

    // Topic-based collections (using entities)
    const entities = newItem.entities || [];
    entities.forEach(entity => {
      if (entity.type === 'organization' || entity.type === 'person') {
        const relatedItems = recentItems.filter(item => 
          item.content.toLowerCase().includes(entity.value.toLowerCase()) && 
          item.id !== newItem.id
        );

        if (relatedItems.length >= 1) {
          analyses.push({
            name: `${entity.value} Collection`,
            description: `Content related to ${entity.value}`,
            confidence: 0.75,
            relatedItems: [newItem.id, ...relatedItems.map(item => item.id)],
            tags: ['entity', entity.type, entity.value.toLowerCase()]
          });
        }
      }
    });

    // Code-based collections
    if (this.looksLikeCode(newItem.content)) {
      const codeItems = recentItems.filter(item => 
        this.looksLikeCode(item.content) && item.id !== newItem.id
      );

      if (codeItems.length >= 2) {
        const language = this.detectCodeLanguage(newItem.content);
        analyses.push({
          name: `${language} Code Snippets`,
          description: `Code snippets and examples in ${language}`,
          confidence: 0.85,
          relatedItems: [newItem.id, ...codeItems.map(item => item.id)],
          tags: ['code', language.toLowerCase(), 'snippets']
        });
      }
    }

    return analyses;
  }

  private extractDomain(url: string): string | null {
    try {
      const urlObj = new URL(url);
      return urlObj.hostname.replace('www.', '');
    } catch {
      const match = url.match(/https?:\/\/(?:www\.)?([^\/]+)/);
      return match ? match[1] : null;
    }
  }

  private looksLikeCode(content: string): boolean {
    const codeIndicators = [
      /function\s+\w+\s*\(/,
      /class\s+\w+/,
      /import\s+.+from/,
      /const\s+\w+\s*=/,
      /def\s+\w+\s*\(/,
      /<\w+[^>]*>/,
      /\{\s*\w+:\s*.+\}/
    ];

    return codeIndicators.some(pattern => pattern.test(content));
  }

  private detectCodeLanguage(content: string): string {
    if (/function\s+\w+|const\s+\w+|let\s+\w+/.test(content)) return 'JavaScript';
    if (/def\s+\w+|import\s+\w+|class\s+\w+.*:/.test(content)) return 'Python';
    if (/<\w+[^>]*>/.test(content)) return 'HTML';
    if (/public\s+class|private\s+\w+/.test(content)) return 'Java';
    if (/fn\s+\w+|let\s+mut/.test(content)) return 'Rust';
    return 'Code';
  }

  private async findExistingCollection(userId: string, name: string): Promise<ClipboardCollection | null> {
    const pool = getPool();
    const result = await pool.query(
      'SELECT * FROM clipboard_collections WHERE user_id = $1 AND name ILIKE $2',
      [userId, `%${name}%`]
    );

    return result.rows.length > 0 ? result.rows[0] : null;
  }

  async deleteCollection(collectionId: string, userId: string): Promise<void> {
    const pool = getPool();
    
    await pool.query('BEGIN');
    try {
      // Delete collection items
      await pool.query('DELETE FROM collection_items WHERE collection_id = $1', [collectionId]);
      
      // Delete collection
      await pool.query(
        'DELETE FROM clipboard_collections WHERE id = $1 AND user_id = $2',
        [collectionId, userId]
      );
      
      await pool.query('COMMIT');
    } catch (error) {
      await pool.query('ROLLBACK');
      throw error;
    }
  }

  async updateCollection(
    collectionId: string, 
    userId: string, 
    updates: Partial<ClipboardCollection>
  ): Promise<ClipboardCollection> {
    const pool = getPool();
    
    const result = await pool.query(
      `UPDATE clipboard_collections 
       SET name = COALESCE($3, name),
           description = COALESCE($4, description),
           tags = COALESCE($5, tags),
           updated_at = NOW()
       WHERE id = $1 AND user_id = $2
       RETURNING *`,
      [collectionId, userId, updates.name, updates.description, updates.tags]
    );

    if (result.rows.length === 0) {
      throw new Error('Collection not found');
    }

    return result.rows[0];
  }
}

export const collectionsService = new CollectionsService();