import React, { useState, useEffect } from 'react';
import { FolderIcon, PlusIcon, TrashIcon, TagIcon, SparklesIcon } from '@heroicons/react/24/outline';
import { Button } from './ui/Button';
import { LoadingSpinner } from './ui/LoadingSpinner';
import { ClipboardCollection, ClipboardItem } from '../../../shared/types';

interface CollectionsManagerProps {
  onSelectCollection: (collection: ClipboardCollection) => void;
  onCreateCollection: (name: string, description?: string) => void;
}

export function CollectionsManager({ onSelectCollection, onCreateCollection }: CollectionsManagerProps) {
  const [collections, setCollections] = useState<ClipboardCollection[]>([]);
  const [loading, setLoading] = useState(true);
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [newCollectionName, setNewCollectionName] = useState('');
  const [newCollectionDescription, setNewCollectionDescription] = useState('');
  const [suggestions, setSuggestions] = useState<ClipboardCollection[]>([]);

  useEffect(() => {
    loadCollections();
  }, []);

  const loadCollections = async () => {
    try {
      const response = await fetch('/api/collections', {
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('token')}`
        }
      });
      
      if (response.ok) {
        const data = await response.json();
        setCollections(data.data || []);
      }
    } catch (error) {
      console.error('Error loading collections:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateCollection = async () => {
    if (!newCollectionName.trim()) return;

    try {
      const response = await fetch('/api/collections', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('token')}`
        },
        body: JSON.stringify({
          name: newCollectionName,
          description: newCollectionDescription || undefined
        })
      });

      if (response.ok) {
        const data = await response.json();
        setCollections(prev => [data.data, ...prev]);
        setNewCollectionName('');
        setNewCollectionDescription('');
        setShowCreateForm(false);
        onCreateCollection(newCollectionName, newCollectionDescription);
      }
    } catch (error) {
      console.error('Error creating collection:', error);
    }
  };

  const handleDeleteCollection = async (collectionId: string) => {
    if (!confirm('Are you sure you want to delete this collection?')) return;

    try {
      const response = await fetch(`/api/collections/${collectionId}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('token')}`
        }
      });

      if (response.ok) {
        setCollections(prev => prev.filter(c => c.id !== collectionId));
      }
    } catch (error) {
      console.error('Error deleting collection:', error);
    }
  };

  const getSuggestionsForItem = async (item: ClipboardItem) => {
    try {
      const response = await fetch('/api/collections/suggest', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('token')}`
        },
        body: JSON.stringify({
          itemId: item.id,
          content: item.content,
          contentType: item.contentType
        })
      });

      if (response.ok) {
        const data = await response.json();
        setSuggestions(data.data || []);
      }
    } catch (error) {
      console.error('Error getting collection suggestions:', error);
    }
  };

  const acceptSuggestion = async (suggestion: ClipboardCollection) => {
    try {
      const response = await fetch('/api/collections', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('token')}`
        },
        body: JSON.stringify({
          name: suggestion.name,
          description: suggestion.description,
          autoGenerated: true
        })
      });

      if (response.ok) {
        const data = await response.json();
        setCollections(prev => [data.data, ...prev]);
        setSuggestions(prev => prev.filter(s => s.id !== suggestion.id));
      }
    } catch (error) {
      console.error('Error accepting suggestion:', error);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center p-8">
        <LoadingSpinner size="lg" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-semibold text-gray-900 flex items-center">
          <FolderIcon className="h-6 w-6 mr-2" />
          Collections
        </h2>
        <Button
          onClick={() => setShowCreateForm(true)}
          size="sm"
          className="flex items-center"
        >
          <PlusIcon className="h-4 w-4 mr-1" />
          New Collection
        </Button>
      </div>

      {/* AI Suggestions */}
      {suggestions.length > 0 && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <div className="flex items-center mb-3">
            <SparklesIcon className="h-5 w-5 text-blue-600 mr-2" />
            <h3 className="font-medium text-blue-900">AI Suggestions</h3>
          </div>
          <div className="space-y-2">
            {suggestions.map((suggestion) => (
              <div key={suggestion.id} className="flex items-center justify-between bg-white p-3 rounded border">
                <div>
                  <h4 className="font-medium text-gray-900">{suggestion.name}</h4>
                  <p className="text-sm text-gray-600">{suggestion.description}</p>
                </div>
                <div className="flex space-x-2">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => setSuggestions(prev => prev.filter(s => s.id !== suggestion.id))}
                  >
                    Dismiss
                  </Button>
                  <Button
                    size="sm"
                    onClick={() => acceptSuggestion(suggestion)}
                  >
                    Create
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Create Form */}
      {showCreateForm && (
        <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
          <h3 className="font-medium text-gray-900 mb-3">Create New Collection</h3>
          <div className="space-y-3">
            <input
              type="text"
              value={newCollectionName}
              onChange={(e) => setNewCollectionName(e.target.value)}
              placeholder="Collection name"
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
            <textarea
              value={newCollectionDescription}
              onChange={(e) => setNewCollectionDescription(e.target.value)}
              placeholder="Description (optional)"
              rows={2}
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
            <div className="flex space-x-2">
              <Button onClick={handleCreateCollection} disabled={!newCollectionName.trim()}>
                Create
              </Button>
              <Button variant="outline" onClick={() => setShowCreateForm(false)}>
                Cancel
              </Button>
            </div>
          </div>
        </div>
      )}

      {/* Collections List */}
      <div className="space-y-2">
        {collections.length === 0 ? (
          <div className="text-center py-8 text-gray-500">
            <FolderIcon className="h-12 w-12 mx-auto mb-4 text-gray-300" />
            <p>No collections yet</p>
            <p className="text-sm">Create your first collection to organize clipboard items</p>
          </div>
        ) : (
          collections.map((collection) => (
            <div
              key={collection.id}
              className="bg-white border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow cursor-pointer"
              onClick={() => onSelectCollection(collection)}
            >
              <div className="flex items-center justify-between">
                <div className="flex-1">
                  <div className="flex items-center">
                    <FolderIcon className="h-5 w-5 text-gray-400 mr-2" />
                    <h3 className="font-medium text-gray-900">{collection.name}</h3>
                    {collection.autoGenerated && (
                      <SparklesIcon className="h-4 w-4 text-blue-500 ml-2" title="AI Generated" />
                    )}
                  </div>
                  {collection.description && (
                    <p className="text-sm text-gray-600 mt-1">{collection.description}</p>
                  )}
                  <div className="flex items-center mt-2 text-xs text-gray-500">
                    <span>{collection.items.length} items</span>
                    <span className="mx-2">•</span>
                    <span>Updated {new Date(collection.updatedAt).toLocaleDateString()}</span>
                  </div>
                  {collection.tags.length > 0 && (
                    <div className="flex items-center mt-2">
                      <TagIcon className="h-3 w-3 text-gray-400 mr-1" />
                      <div className="flex space-x-1">
                        {collection.tags.map((tag, index) => (
                          <span key={index} className="text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded">
                            {tag}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={(e) => {
                    e.stopPropagation();
                    handleDeleteCollection(collection.id);
                  }}
                  className="text-red-600 hover:text-red-700"
                >
                  <TrashIcon className="h-4 w-4" />
                </Button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}