import { Router, Request, Response } from 'express';
import { body, param, query, validationResult } from 'express-validator';
import { collectionsService } from '../services/collectionsService';
import { authMiddleware } from '../middleware/auth';
import { logger } from '../utils/logger';

const router = Router();

// Apply authentication to all routes
router.use(authMiddleware);

// Get user collections
router.get('/', async (req: Request, res: Response) => {
  try {
    const userId = (req as any).user.id;
    const collections = await collectionsService.getUserCollections(userId);

    res.json({
      success: true,
      data: collections
    });
  } catch (error) {
    logger.error('Error fetching collections:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch collections'
    });
  }
});

// Create new collection
router.post('/',
  [
    body('name').isString().isLength({ min: 1, max: 100 }).trim(),
    body('description').isString().isLength({ max: 500 }).optional(),
    body('autoGenerated').isBoolean().optional()
  ],
  async (req: Request, res: Response) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).json({
          success: false,
          error: 'Validation failed',
          details: errors.array()
        });
      }

      const userId = (req as any).user.id;
      const { name, description, autoGenerated = false } = req.body;

      const collection = await collectionsService.createCollection(
        userId, 
        name, 
        description, 
        autoGenerated
      );

      res.status(201).json({
        success: true,
        data: collection
      });
    } catch (error) {
      logger.error('Error creating collection:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to create collection'
      });
    }
  }
);

// Add item to collection
router.post('/:collectionId/items',
  [
    param('collectionId').isUUID(),
    body('itemId').isUUID()
  ],
  async (req: Request, res: Response) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).json({
          success: false,
          error: 'Validation failed',
          details: errors.array()
        });
      }

      const { collectionId } = req.params;
      const { itemId } = req.body;

      await collectionsService.addItemToCollection(collectionId, itemId);

      res.json({
        success: true,
        message: 'Item added to collection'
      });
    } catch (error) {
      logger.error('Error adding item to collection:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to add item to collection'
      });
    }
  }
);

// Remove item from collection
router.delete('/:collectionId/items/:itemId',
  [
    param('collectionId').isUUID(),
    param('itemId').isUUID()
  ],
  async (req: Request, res: Response) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).json({
          success: false,
          error: 'Validation failed',
          details: errors.array()
        });
      }

      const { collectionId, itemId } = req.params;

      await collectionsService.removeItemFromCollection(collectionId, itemId);

      res.json({
        success: true,
        message: 'Item removed from collection'
      });
    } catch (error) {
      logger.error('Error removing item from collection:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to remove item from collection'
      });
    }
  }
);

// Get collection suggestions for new item
router.post('/suggest',
  [
    body('itemId').isUUID(),
    body('content').isString().isLength({ min: 1, max: 10000 }).trim(),
    body('contentType').isIn(['text', 'url', 'code', 'image']).optional()
  ],
  async (req: Request, res: Response) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).json({
          success: false,
          error: 'Validation failed',
          details: errors.array()
        });
      }

      const userId = (req as any).user.id;
      const { itemId, content, contentType = 'text' } = req.body;

      // Create a mock clipboard item for analysis
      const mockItem = {
        id: itemId,
        userId,
        content,
        contentType,
        metadata: { category: 'other' as const, confidence: 1 },
        entities: [],
        suggestions: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };

      const suggestions = await collectionsService.suggestCollections(userId, mockItem);

      res.json({
        success: true,
        data: suggestions
      });
    } catch (error) {
      logger.error('Error suggesting collections:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to suggest collections'
      });
    }
  }
);

// Update collection
router.put('/:collectionId',
  [
    param('collectionId').isUUID(),
    body('name').isString().isLength({ min: 1, max: 100 }).trim().optional(),
    body('description').isString().isLength({ max: 500 }).optional(),
    body('tags').isArray().optional()
  ],
  async (req: Request, res: Response) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).json({
          success: false,
          error: 'Validation failed',
          details: errors.array()
        });
      }

      const userId = (req as any).user.id;
      const { collectionId } = req.params;
      const updates = req.body;

      const collection = await collectionsService.updateCollection(collectionId, userId, updates);

      res.json({
        success: true,
        data: collection
      });
    } catch (error) {
      logger.error('Error updating collection:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to update collection'
      });
    }
  }
);

// Delete collection
router.delete('/:collectionId',
  [param('collectionId').isUUID()],
  async (req: Request, res: Response) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).json({
          success: false,
          error: 'Validation failed',
          details: errors.array()
        });
      }

      const userId = (req as any).user.id;
      const { collectionId } = req.params;

      await collectionsService.deleteCollection(collectionId, userId);

      res.json({
        success: true,
        message: 'Collection deleted'
      });
    } catch (error) {
      logger.error('Error deleting collection:', error);
      res.status(500).json({
        success: false,
        error: 'Failed to delete collection'
      });
    }
  }
);

export { router as collectionsRoutes };