export interface User {
    id: string;
    email: string;
    firebaseUid: string;
    preferences: UserPreferences;
    createdAt: string;
    updatedAt: string;
}
export interface UserPreferences {
    enableNotifications: boolean;
    autoSync: boolean;
    maxHistoryItems: number;
    enableAI: boolean;
}
export interface ClipboardItem {
    id: string;
    userId: string;
    content: string;
    contentType: 'text' | 'image' | 'file' | 'url';
    metadata: ClipboardMetadata;
    entities: DetectedEntity[];
    suggestions: ActionSuggestion[];
    createdAt: string;
    updatedAt: string;
    deviceId?: string;
    isPinned?: boolean;
    collectionId?: string;
    transformations?: ContentTransformation[];
    stagingGroup?: string;
}
export interface ClipboardMetadata {
    sourceApp?: string;
    deviceId?: string;
    category: ContentCategory;
    confidence: number;
    size?: number;
    mimeType?: string;
}
export interface DetectedEntity {
    type: EntityType;
    value: string;
    confidence: number;
    startIndex: number;
    endIndex: number;
}
export interface ActionSuggestion {
    id: string;
    type: ActionType;
    title: string;
    description: string;
    icon: string;
    confidence: number;
    metadata: Record<string, any>;
}
export type EntityType = 'email' | 'phone' | 'address' | 'date' | 'time' | 'url' | 'person' | 'organization' | 'location' | 'credit_card' | 'code';
export type ContentCategory = 'contact' | 'event' | 'location' | 'document' | 'media' | 'code' | 'other';
export type ActionType = 'open_maps' | 'create_event' | 'call_phone' | 'send_email' | 'open_url' | 'add_contact' | 'create_note' | 'search_web' | 'generate_email' | 'create_task_list' | 'expand_idea' | 'summarize_bullets' | 'professional_tone' | 'translate' | 'fix_grammar' | 'remove_background' | 'enhance_image' | 'smart_paste' | 'open_app';
export interface AIProcessingResult {
    entities: DetectedEntity[];
    category: ContentCategory;
    suggestions: ActionSuggestion[];
    confidence: number;
}
export interface SyncEvent {
    type: 'clipboard_added' | 'clipboard_updated' | 'clipboard_deleted';
    userId: string;
    itemId: string;
    data?: any;
    timestamp: string;
}
export interface ApiResponse<T = any> {
    success: boolean;
    data?: T;
    error?: string;
    message?: string;
}
export interface ContentTransformation {
    id: string;
    type: 'summarize' | 'translate' | 'tone_change' | 'grammar_fix' | 'expand' | 'format';
    originalContent: string;
    transformedContent: string;
    confidence: number;
    metadata: Record<string, any>;
}
export interface ClipboardCollection {
    id: string;
    userId: string;
    name: string;
    description?: string;
    items: string[];
    tags: string[];
    createdAt: string;
    updatedAt: string;
    autoGenerated: boolean;
}
export interface StagingArea {
    id: string;
    userId: string;
    items: ClipboardItem[];
    targetFormat: 'contact' | 'email' | 'document' | 'custom';
    createdAt: string;
}
export interface SmartPasteFormat {
    format: 'plain' | 'rich' | 'markdown' | 'html' | 'citation';
    content: string;
    confidence: number;
}
//# sourceMappingURL=index.d.ts.map